apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: appwrite
  name: appwrite-certificates
  labels:
    app: appwrite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi