apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite-telegraf
  namespace: appwrite
  labels:
    app: appwrite-telegraf
spec:
  selector:
    matchLabels:
      app: appwrite-telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: appwrite-telegraf
    spec:
      containers:
        - image: appwrite/telegraf:1.4.0
          imagePullPolicy: IfNotPresent
          name: telegraf
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: false
          ports:
            - containerPort: 8125
          env:
            - name: _APP_INFLUXDB_HOST
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_INFLUXDB_HOST
            - name: _APP_INFLUXDB_PORT
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_INFLUXDB_PORT

