apiVersion: v1
kind: Service
metadata:
  namespace: appwrite
  name: appwrite-influxdb
spec:
  selector:
    app: appwrite-influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
