apiVersion: v1
kind: Service
metadata:
  namespace: appwrite
  name: appwrite-mariadb
spec:
  selector:
    app: appwrite-mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort