apiVersion: v1
kind: Service
metadata:
  namespace: appwrite
  name: appwrite-telegraf
spec:
  selector:
    app: appwrite-telegraf
  ports:
    - protocol: TCP
      port: 8125
      targetPort: 8125
