apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite-schedule
  labels:
    app: appwrite
spec:
  selector:
    matchLabels:
      app: appwrite
  replicas: 1
  template:
    metadata:
      name: appwrite-schedule
      labels:
        app: appwrite
    spec:
      containers:
        - name: appwrite-schedule
          image: appwrite/appwrite:1.4.13
          imagePullPolicy: IfNotPresent
          command:
            - "schedule"
          env:
            - name: _APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_ENV
            - name: _APP_WORKER_PER_CORE
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_WORKER_PER_CORE
            - name: _APP_OPENSSL_KEY_V1
              valueFrom:
                secretKeyRef:
                  name: appwrite-secrets
                  key: _APP_OPENSSL_KEY_V1
            - name: _APP_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_REDIS_HOST
            - name: _APP_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_REDIS_PORT
            - name: _APP_REDIS_USER
              valueFrom:
                secretKeyRef:
                  name: appwrite-secrets
                  key: _APP_REDIS_USER
            - name: _APP_REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: appwrite-secrets
                  key: _APP_REDIS_PASS
            - name: _APP_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DB_HOST
            - name: _APP_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DB_PORT
            - name: _APP_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DB_SCHEMA
            - name: _APP_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DB_USER
            - name: _APP_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: appwrite-secrets
                  key: _APP_DB_PASS
