apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite-realtime
  namespace: appwrite
  labels:
    app: appwrite-realtime
spec:
  selector:
    matchLabels:
      app: appwrite-realtime
  replicas: 1
  template:
    metadata:
      name: appwrite-realtime
      labels:
        app: appwrite-realtime
    spec:
      containers:
        - name: appwrite-realtime
          image: appwrite/appwrite:1.4.13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          command:
            - "realtime"
          env:
            - name: _APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_ENV
            - name: _APP_WORKER_PER_CORE
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_WORKER_PER_CORE
            - name: _APP_OPTIONS_ABUSE
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_OPTIONS_ABUSE
            - name: _APP_OPTIONS_ROUTER_PROTECTION
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_OPTIONS_ROUTER_PROTECTION
            - name: _APP_OPENSSL_KEY_V1
              valueFrom:
                secretKeyRef:
                  name: appwrite-secrets
                  key: _APP_OPENSSL_KEY_V1
            - name: _APP_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_REDIS_HOST
            - name: _APP_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_REDIS_PORT
            - name: _APP_REDIS_USER
              valueFrom:
                secretKeyRef:
                  name: appwrite-secrets
                  key: _APP_REDIS_USER
            - name: _APP_REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: appwrite-secrets
                  key: _APP_REDIS_PASS
            - name: _APP_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DB_HOST
            - name: _APP_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DB_PORT
            - name: _APP_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DB_SCHEMA
            - name: _APP_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DB_USER
            - name: _APP_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: appwrite-secrets
                  key: _APP_DB_PASS
            - name: _APP_USAGE_STATS
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_USAGE_STATS
            - name: _APP_LOGGING_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_LOGGING_PROVIDER
            - name: _APP_LOGGING_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_LOGGING_CONFIG