apiVersion: v2
name: Appwriet
description: A Helm chart for Appwrite

type: application
version: 0.0.1
appVersion: "1.4.13"

dependencies:
  - name: mariadb
    version: 16.3.2
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 18.6.1
    repository: https://charts.bitnami.com/bitnami
  - name: influxdb
    version: 5.1.17
    repository: https://charts.bitnami.com/bitnami
    condition: appwrite.usages
  - name: telegraf
    version: 1.8.42
    repository: https://helm.influxdata.com/
    condition: appwrite.usages