apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite-certificates
  namespace: appwrite
  labels:
    app: appwrite
spec:
  selector:
    matchLabels:
      app: appwrite
  replicas: 1
  template:
    metadata:
      name: appwrite-certificates
      labels:
        app: appwrite
    spec:
      containers:
        - name: appwrite-certificates
          image: appwrite/appwrite:1.4.13
          imagePullPolicy: IfNotPresent
          command:
            - "worker-certificates"
          env:
            - name: _APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_ENV
            - name: _APP_WORKER_PER_CORE
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_WORKER_PER_CORE
            - name: _APP_OPENSSL_KEY_V1
              valueFrom:
                secretKeyRef:
                  name: appwrite-secrets
                  key: _APP_OPENSSL_KEY_V1
            - name: _APP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DOMAIN
            - name: _APP_DOMAIN_TARGET
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DOMAIN_TARGET
            - name: _APP_DOMAIN_FUNCTIONS
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DOMAIN_FUNCTIONS
            - name: _APP_SYSTEM_SECURITY_EMAIL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_SYSTEM_SECURITY_EMAIL_ADDRESS
            - name: _APP_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_REDIS_HOST
            - name: _APP_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_REDIS_PORT
            - name: _APP_REDIS_USER
              valueFrom:
                secretKeyRef:
                  name: appwrite-secrets
                  key: _APP_REDIS_USER
            - name: _APP_REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: appwrite-secrets
                  key: _APP_REDIS_PASS
            - name: _APP_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DB_HOST
            - name: _APP_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DB_PORT
            - name: _APP_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DB_SCHEMA
            - name: _APP_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_DB_USER
            - name: _APP_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: appwrite-secrets
                  key: _APP_DB_PASS
            - name: _APP_LOGGING_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_LOGGING_PROVIDER
            - name: _APP_LOGGING_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: appwrite
                  key: _APP_LOGGING_CONFIG
          volumeMounts:
            - mountPath: /storage/config
              name: appwrite-config
            - mountPath: /storage/certificates
              name: appwrite-certificates
      volumes:
        - name: appwrite-config
          persistentVolumeClaim:
            claimName: appwrite-config
        - name: appwrite-certificates
          persistentVolumeClaim:
            claimName: appwrite-certificates